/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateShiftArgs } from "./CreateShiftArgs";
import { UpdateShiftArgs } from "./UpdateShiftArgs";
import { DeleteShiftArgs } from "./DeleteShiftArgs";
import { ShiftFindManyArgs } from "./ShiftFindManyArgs";
import { ShiftFindUniqueArgs } from "./ShiftFindUniqueArgs";
import { Shift } from "./Shift";
import { ShiftService } from "../shift.service";

@graphql.Resolver(() => Shift)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ShiftResolverBase {
  constructor(
    protected readonly service: ShiftService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "read",
    possession: "any",
  })
  async _shiftsMeta(
    @graphql.Args() args: ShiftFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Shift])
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "read",
    possession: "any",
  })
  async shifts(
    @graphql.Args() args: ShiftFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Shift[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Shift",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Shift, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "read",
    possession: "own",
  })
  async shift(
    @graphql.Args() args: ShiftFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Shift | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Shift",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Shift)
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "create",
    possession: "any",
  })
  async createShift(
    @graphql.Args() args: CreateShiftArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Shift> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Shift",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Shift"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Shift)
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "update",
    possession: "any",
  })
  async updateShift(
    @graphql.Args() args: UpdateShiftArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Shift | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Shift",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Shift"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Shift)
  @nestAccessControl.UseRoles({
    resource: "Shift",
    action: "delete",
    possession: "any",
  })
  async deleteShift(
    @graphql.Args() args: DeleteShiftArgs
  ): Promise<Shift | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
